name: Examen HTML EcoBook - Validación Detallada
on: [push]

jobs:
  evaluar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Inicializar variables
      - name: Configurar entorno
        id: config
        run: |
          echo "puntaje=0" >> $GITHUB_ENV
          echo "errores=''" >> $GITHUB_ENV
          echo "max_puntaje=100" >> $GITHUB_ENV
          echo "aprobado=false" >> $GITHUB_ENV
      # funcion para agregar mensajes
      - name: Configurar funciones de mensajes
        id: funciones
        run: |
          echo "::group::📌 Resumen de Validación"
          echo "Comenzando validación del proyecto..."
          echo "::endgroup::"
      # ========================
      # 1. VALIDACIÓN DE ESTRUCTURA (15%)
      # ========================
      - name: Validar estructura de carpetas
        run: |
          echo "::group::📂 Validando estructura de carpetas"
          # Assets debe contener imágenes
          if [ ! -d "assets" ]; then
            echo "::error::❌ Falta carpeta 'assets' (-3 puntos)"
            echo "errores+='❌ Falta completamente la carpeta assets\n'" >> $GITHUB_ENV
          else
            if [ -z "$(find assets -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.svg' \))" ]; then
              echo "::error::❌ Carpeta 'assets' no contiene imágenes (-3 puntos)"
              echo "errores+='❌ La carpeta assets no tiene archivos de imagen\n'" >> $GITHUB_ENV
            else
              echo "✅ Carpeta 'assets' con imágenes encontrada (+3 puntos)"
              echo "exitos+='✅ Carpeta assets válida\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
            fi
          fi

          # CSS debe tener archivos
          if [ ! -d "css" ]; then
            echo "::error::❌ Falta carpeta 'css' (-3 puntos)"
            echo "errores+='❌ Falta completamente la carpeta css\n'" >> $GITHUB_ENV
          else
            if [ -z "$(find css -name '*.css')" ]; then
              echo "::error::❌ Carpeta 'css' no contiene archivos CSS (-3 puntos)"
              echo "errores+='❌ La carpeta css está vacía\n'" >> $GITHUB_ENV
            else
              echo "✅ Carpeta 'css' con archivos encontrados (+3 puntos)"
              echo "exitos+='✅ Carpeta css válida\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
            fi
          fi

          # JS debe tener archivos (opcional)
          if [ -d "js" ] && [ -z "$(find js -name '*.js')" ]; then
            echo "::warning::⚠️ Carpeta 'js' está vacía (pero no afecta puntaje)"
          fi

          # Validar páginas
          paginas=("alojamientos" "contacto" "registro")
          for pagina in "${paginas[@]}"; do
            if [ ! -f "pages/$pagina.html" ]; then
              echo "::error::❌ Falta archivo pages/$pagina.html (-3 puntos)"
              echo "errores+='❌ Falta archivo pages/$pagina.html\n'" >> $GITHUB_ENV
            else
              echo "✅ Archivo pages/$pagina.html encontrado (+3 puntos)"
              echo "exitos+='✅ Archivo pages/$pagina.html presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
            fi
          done

      # ========================
      # 2. VALIDACIÓN index.html (20%)
      # ========================
      - name: Validar index.html
        run: |
          # Verificar estructura semántica
          etiquetas=("header" "nav" "main" "article" "section" "footer")
          for etiqueta in "${etiquetas[@]}"; do
            if ! grep -q "<$etiqueta" index.html; then
              echo "::error::❌ Falta etiqueta <$etiqueta> en index.html (-2 puntos)"
              echo "errores+='❌ Falta etiqueta <$etiqueta> en index.html\n'" >> $GITHUB_ENV
            else
              echo "✅ Etiqueta <$etiqueta> encontrada (+2 puntos)"
              echo "exitos+='✅ Etiqueta <$etiqueta> presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 2 ))" >> $GITHUB_ENV
            fi
          done

          # Verificar navegación
          paginas=("alojamientos" "contacto" "registro")
          for pagina in "${paginas[@]}"; do
            if ! grep -q "href=\"pages/$pagina.html\"" index.html; then
              echo "::error::❌ Falta link a $pagina.html en menú (-1 punto)"
              echo "errores+='❌ Falta link a $pagina.html en menú\n'" >> $GITHUB_ENV
            else
              echo "✅ Link a $pagina.html encontrado (+1 punto)"
              echo "exitos+='✅ Link a $pagina.html presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 1 ))" >> $GITHUB_ENV
            fi
          done

          # Verificar cards de alojamientos
          if ! grep -q "<figure>" index.html || [ $(grep -c "<figure>" index.html) -lt 2 ]; then
            echo "::error::❌ Debe haber al menos 2 alojamientos con <figure> (-3 puntos)"
            echo "errores+='❌ Faltan cards de alojamientos en index.html\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiquetas <figure> encontrado (+3 punto)"
            echo "exitos+='✅ Etiquetas  <figure> presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
          fi

          # Verificar enlaces en footer
          if ! grep -q "href=\"pages/contacto.html\"" index.html || ! grep -q "href=\"pages/registro.html\"" index.html; then
            echo "::error::❌ Footer debe tener links a Contacto y Registro (-2 puntos)"
            echo "errores+='❌ Enlaces faltantes en footer\n'" >> $GITHUB_ENV
          else
            echo "✅ Link a $contacto.html y $registro.html encontrado (+2 punto)"
            echo "exitos+='✅ Link a $contacto.html y $registro.html presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 2 ))" >> $GITHUB_ENV
          fi

      # ========================
      # 3. VALIDACIÓN alojamientos.html (20%)
      # ========================
      - name: Validar alojamientos.html
        run: |
          # Verificar tabla
          columnas=("Nombre" "Ubicación" "Precio/noche")
          for columna in "${columnas[@]}"; do
            if ! grep -q "<th>$columna</th>" pages/alojamientos.html; then
              echo "::error::❌ Falta columna '$columna' en tabla (-3 puntos)"
              echo "errores+='❌ Falta columna $columna en tabla\n'" >> $GITHUB_ENV
            else
              echo "✅ Columna $columna encontrado (+3 punto)"
              echo "exitos+='✅ $columna presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
            fi
          done

          # Verificar al menos un registro
          if ! grep -q "<tr>.*<td>.*</td>.*<td>.*</td>.*<td>.*</td>.*</tr>" pages/alojamientos.html; then
            echo "::error::❌ Tabla debe tener al menos un registro (-3 puntos)"
            echo "errores+='❌ Tabla sin registros\n'" >> $GITHUB_ENV
          else
            echo "✅ Registro en tabla encontrado (+3 punto)"
            echo "exitos+='✅ Registro en tabla\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
          fi

          # Verificar aside
          if ! grep -q "<aside>" pages/alojamientos.html || ! grep -q "<ul>" pages/alojamientos.html; then
            echo "::error::❌ Falta sección 'Tips eco-friendly' con lista (-4 puntos)"
            echo "errores+='❌ Falta aside con tips\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiqueta <ul> dentro de <aside> encontrado (+4 punto)"
            echo "exitos+='✅ Etiqueta <ul> presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 4 ))" >> $GITHUB_ENV
          fi

      # ========================
      # 4. VALIDACIÓN contacto.html (15%)
      # ========================
      - name: Validar contacto.html
        run: |
          # Verificar formulario
          campos=(
            'name="nombre".*type="text"'
            'name="email".*type="email"'
            'name="mensaje".*<textarea'
          )
          for campo in "${campos[@]}"; do
            if ! grep -Pq "$campo" pages/contacto.html; then
              echo "::error::❌ Campo incorrecto en formulario de contacto (-2 puntos)"
              echo "errores+='❌ Campo faltante en formulario de contacto\n'" >> $GITHUB_ENV
            else
              echo "✅ $campo en formulario encontrado (+2 punto)"
              echo "exitos+='✅ $campo presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 2 ))" >> $GITHUB_ENV
            fi
          done

          # Verificar address
          if ! grep -q "<address>" pages/contacto.html || ! grep -q "contacto@ecobook.com" pages/contacto.html; then
            echo "::error::❌ Falta información de contacto en <address> (-3 puntos)"
            echo "errores+='❌ Falta address con información\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiqueta <address> encontrado (+3 punto)"
            echo "exitos+='✅ <address> presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
          fi

      # ========================
      # 5. VALIDACIÓN registro.html (25%)
      # ========================
      - name: Validar registro.html
        run: |
          # Verificar estructura del formulario
          if ! grep -q "<fieldset>" pages/registro.html || ! grep -q "<legend>" pages/registro.html; then
            echo "::error::❌ Formulario debe tener <fieldset> y <legend> (-5 puntos)"
            echo "errores+='❌ Falta estructura fieldset/legend en formulario\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiquetaa <fieldset> y <legend> encontrado (+5 punto)"
            echo "exitos+='✅ Etiquetaa <fieldset> y <legend> presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 5 ))" >> $GITHUB_ENV
          fi

          # Verificar campos obligatorios
          campos=(
            'name="nombre".*type="text".*required'
            'name="email".*type="email".*required'
            'name="password".*type="password".*required'
            'name="terminos".*type="checkbox".*required'
          )
          for campo in "${campos[@]}"; do
            if ! grep -Pq "$campo" pages/registro.html; then
              echo "::error::❌ Campo requerido faltante o mal configurado (-3 puntos)"
              echo "errores+='❌ Campo requerido faltante en registro\n'" >> $GITHUB_ENV
            else
              echo "✅ $campo requerido encontrado (+3 punto)"
              echo "exitos+='✅ $campo requerido presente\n'" >> $GITHUB_ENV
              echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
            fi
          done

          # Verificar etiquetas y placeholders
          if ! grep -q "<label" pages/registro.html || ! grep -q "placeholder" pages/registro.html; then
            echo "::error::❌ Falta etiquetas label o placeholders (-4 puntos)"
            echo "errores+='❌ Falta accesibilidad en formulario (labels/placeholders)\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiquetas <label> o "placeholder" encontrado (+4 punto)"
            echo "exitos+='✅ Etiquetas <label> o "placeholder" presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 4 ))" >> $GITHUB_ENV
          fi

          # Verificar botón de envío
          if ! grep -q '<button type="submit"' pages/registro.html; then
            echo "::error::❌ Falta botón de envío (-2 puntos)"
            echo "errores+='❌ Falta botón de submit\n'" >> $GITHUB_ENV
          else
            echo "✅ Etiquetas <button> encontrado (+2 punto)"
            echo "exitos+='✅ Etiquetas <button> presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 2 ))" >> $GITHUB_ENV
          fi

      # ========================
      # 6. VALIDACIÓN ADICIONAL (5%)
      # ========================
      - name: Validación extra
        run: |
          # Verificar enlaces a CSS/JS
          if ! grep -q '<link.*css/' index.html; then
            echo "::error::❌ No se enlaza archivo CSS (-2 puntos)"
            echo "errores+='❌ Falta enlace a archivo CSS\n'" >> $GITHUB_ENV
          else
            echo "✅ Archivo CSS enlazado encontrado (+2 punto)"
            echo "exitos+='✅ Archivo CSS enlazado presente\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 2 ))" >> $GITHUB_ENV
          fi

          # Verificar uso de divs prohibidos
          if grep -q '<div.*id="header"' index.html || grep -q '<div.*id="footer"' index.html; then
            echo "::error::❌ No uses <div> para header/footer (-3 puntos)"
            echo "errores+='❌ Uso incorrecto de divs para secciones semánticas\n'" >> $GITHUB_ENV
          else
            echo "✅ No se encontro <div> prohibidos (+2 punto)"
            echo "exitos+='✅ Sin <div> prohibidos\n'" >> $GITHUB_ENV
            echo "puntaje=$(( $puntaje + 3 ))" >> $GITHUB_ENV
          fi

      # ========================
      # RESULTADO FINAL
      # ========================
      - name: Mostrar resultados
        run: |
          porcentaje=$((($puntaje * 100) / $max_puntaje))
          # Convertir a nota 0-20 (regla de tres simple)
          nota=$(echo "scale=1; $puntaje * 20 / 100" | bc)

          echo "::group::📊 RESULTADO FINAL"
          echo "PUNTUACIÓN: $puntaje/$max_puntaje ($porcentaje%)"
          echo "NOTA (0-20): $nota/20"
          echo "PORCENTAJE: $porcentaje%"
          echo ""

          if [ $puntaje -ge 70 ]; then
            echo "🎉 ¡APROBADO! 🎉 (Nota minima: 14/20)"
            echo "aprobado=true" >> $GITHUB_ENV
          else
            echo "❌ REPROBADO - Se necesitan 70 puntos (14/20) para aprobar"
            echo "aprobado=false" >> $GITHUB_ENV
          fi

          echo ""
          echo "✔️ TESTS PASADOS:"
          echo -e "$exitos"
          echo ""
          echo "✖️ ERRORES ENCONTRADOS:"
          echo -e "$errores"
          echo ""
          echo "💡 Consejo: Corrige los errores y vuelve a enviar tu solución"
          echo "::endgroup::"

          # Fallar el workflow si no está aprobado
          if [ "$aprobado" = "false" ]; then
            exit 1
          fi
