name: Validación Examen HTML
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Validar estructura de carpetas
      - name: Verificar carpetas obligatorias
        run: |
          if [ ! -d "assets" ] || [ ! -d "css" ] || [ ! -d "pages" ]; then
            echo "::error::❌ Estructura incorrecta. Faltan: assets/, css/ o pages/"
            exit 1
          fi

      # Validar archivos HTML obligatorios
      - name: Verificar archivos HTML
        run: |
          if [ ! -f "index.html" ] || [ ! -f "pages/registro.html" ]; then
            echo "::error::❌ Faltan archivos: index.html o pages/registro.html"
            exit 1
          fi

      # Validar semántica HTML (opcional)
      - name: Validar HTML semántico
        run: |
          npm install -g html-validate
          html-validate index.html pages/*.html || exit 1
